#!/usr/bin/env node
// DSH Collab-Canvas · bundle builder
// Concatenates src/<kind>/*.js (sorted by filename) into dist/<kind>.js,
// output as a proper cordis composition module: export const name/inject/apply.
// Usage: node tools/build.js
'use strict'
const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const DIST = path.join(ROOT, 'dist')
if (!fs.existsSync(DIST)) fs.mkdirSync(DIST)

// 只构建 host：src/host/*.js → dist/host.js（cordis composition 模块）。
// 客户端不走这里 —— lib/client.js 是独立的 __ModuleLoader__.load 模块，
// 源文件是 src/client/editor-panel.js，由人工/脚本直接同步（见 README/DEV-GUIDE）。
// 历史遗留：src/client/00-*.js ~ 99-*.js 曾是「cordis composition 版客户端」的源码，
// 2026-09-12 确认 package.json 的 exports 与 cordis.patch.yml 都不再引用
// dist/client.js，整套已删除。需要考古可查 git 历史。
const EXCLUDE = {
  host: []
}

function build(kind, name, inject, imports) {
  const dir = path.join(ROOT, 'src', kind)
  const skip = EXCLUDE[kind] || []
  const files = fs.readdirSync(dir)
    .filter(function (f) { return f.endsWith('.js') && skip.indexOf(f) < 0 })
    .sort()
  if (!files.length) throw new Error('no modules in ' + dir)
  let body = files.map(function (f) {
    return '\n    // ==================== ' + f + ' ====================\n' +
      fs.readFileSync(path.join(dir, f), 'utf8').trim()
  }).join('\n')
  // Convert template literal EDITOR_PANEL_JS to regular string (backticks break ESM)
  body = body.replace(
    /const EDITOR_PANEL_JS = `([\s\S]*?)`/m,
    function (match, content) {
      // Escape for single-quoted string: backslashes, single quotes, newlines
      const escaped = content
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
      return "const EDITOR_PANEL_JS = '" + escaped + "'"
    }
  )
  // cordis composition 插件规范：export const name/inject + export function apply(ctx, config)
  const injStr = JSON.stringify(inject)
  const head = (imports || []).join('\n') + '\n'
  const out = '// DSH Collab-Canvas · ' + kind + ' bundle — GENERATED by tools/build.js\n' +
    '// DO NOT EDIT directly. Edit src/' + kind + '/*.js and re-run: node tools/build.js\n' +
    head +
    "export const name = '" + name + "'\n" +
    'export const inject = ' + injStr + '\n' +
    'export function apply(ctx, config) {\n' +
    body + '\n}\n'
  const target = path.join(DIST, kind + '.js')
  fs.writeFileSync(target, out)
  console.log('built', path.relative(ROOT, target), 'from', files.length, 'modules,', out.length, 'chars')
}

// Host 插件：注册 canvas 工具 + 持久化；用 ctx.tools 而非 harness
build('host', 'collab-canvas-host', ['timer', 'tools', 'fs', 'webServer', 'systemPrompt'], [
  'import { defineTool } from "@deepseek-ai/dsh-tools"',
  'import nodefs from "node:fs"',
  'import path from "node:path"',
  'import { exec, execFile, spawn } from "node:child_process"'
])
// 客户端 bundle（build('client', …)）已于 2026-09-12 移除：
// dist/client.js 无人引用，客户端实际走 lib/client.js。
