#!/usr/bin/env node
// DSH Collab-Canvas · bundle builder
// Concatenates src/<kind>/*.js (sorted by filename) into dist/<kind>.js,
// output as a proper cordis composition module: export const name/inject/apply.
// Usage: node tools/build.js
'use strict'
const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const DIST = path.join(ROOT, 'dist')
if (!fs.existsSync(DIST)) fs.mkdirSync(DIST)

// src/client 下混着两种客户端入口，不能一起拼：
//   · 00-*.js ~ 99-*.js：cordis composition 模块，拼进 dist/client.js 的 apply(ctx) 函数体
//   · editor-panel.js：独立的 __ModuleLoader__.load 模块（即 lib/client.js 的源），
//     自带 factory 闭包与 exports.apply，拼进 bundle 会直接语法错乱。
// 所以这里显式排除。
const EXCLUDE = {
  // img-constrain.js 是独立注入的 <script> 资产（IIFE），不是 composition
  // 模块。拼进 bundle 会让它在 apply() 时就跑起来，重复起一个 1s 轮询。
  client: ['editor-panel.js', 'img-constrain.js'],
  host: []
}

function build(kind, name, inject, imports) {
  const dir = path.join(ROOT, 'src', kind)
  const skip = EXCLUDE[kind] || []
  const files = fs.readdirSync(dir)
    .filter(function (f) { return f.endsWith('.js') && skip.indexOf(f) < 0 })
    .sort()
  if (!files.length) throw new Error('no modules in ' + dir)
  let body = files.map(function (f) {
    return '\n    // ==================== ' + f + ' ====================\n' +
      fs.readFileSync(path.join(dir, f), 'utf8').trim()
  }).join('\n')
  // Convert template literal EDITOR_PANEL_JS to regular string (backticks break ESM)
  body = body.replace(
    /const EDITOR_PANEL_JS = `([\s\S]*?)`/m,
    function (match, content) {
      // Escape for single-quoted string: backslashes, single quotes, newlines
      const escaped = content
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
      return "const EDITOR_PANEL_JS = '" + escaped + "'"
    }
  )
  // cordis composition 插件规范：export const name/inject + export function apply(ctx, config)
  const injStr = JSON.stringify(inject)
  const head = (imports || []).join('\n') + '\n'
  const out = '// DSH Collab-Canvas · ' + kind + ' bundle — GENERATED by tools/build.js\n' +
    '// DO NOT EDIT directly. Edit src/' + kind + '/*.js and re-run: node tools/build.js\n' +
    head +
    "export const name = '" + name + "'\n" +
    'export const inject = ' + injStr + '\n' +
    'export function apply(ctx, config) {\n' +
    body + '\n}\n'
  const target = path.join(DIST, kind + '.js')
  fs.writeFileSync(target, out)
  console.log('built', path.relative(ROOT, target), 'from', files.length, 'modules,', out.length, 'chars')
}

// Host 插件：注册 canvas 工具 + 持久化；用 ctx.tools 而非 harness
build('host', 'collab-canvas-host', ['timer', 'tools', 'fs', 'webServer', 'systemPrompt'], [
  'import { defineTool } from "@deepseek-ai/dsh-tools"',
  'import nodefs from "node:fs"'
])
// Client 插件：WYSIWYG 编辑 + Slot 注册（Phase 2）
build('client', 'collab-canvas-client', ['slots', 'timer'], [])
